---
- name: Check webserver
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "https://azcanbm-prod01/webui/"
        delay: 60
        verify_ssl: false
  rules:
    - name: netbackup-service-down
      condition: event.url_check.status == "down"
      actions:
      - run_playbook:
          name: start-netbackup.yml
          set_facts: true
      - run_playbook:
          name: copy-template-toreo.yml
    - name: netbackup-service-up
      condition: event.url_check.status == "up"
      actions:
      - run_playbook:
          name: copy-template-azcapo.yml
