---
- name: Copiar plantilla de configuracion master toreo
  hosts: all
  tasks:
  - name: Copia la plantilla de configuracion toreo a /usr/openv/netbackup/bp.conf
    ansible.builtin.template:
      src: bp.conf-toreo.j2
      dest: /usr/openv/netbackup/bp.conf
      owner: root
      group: root
      mode: '0644'
